version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project
    overwrite: yes

permissions:
  - object: /home/ec2-user/project
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: ec2-user
